
# Preloader
[params.preloader]
enable = false
preloader = "" # use .png , .svg or .gif format


############################ Markup ##############################
[markup]
[markup.goldmark.renderer]
unsafe = true


################################### Footer ############################
[params.footer]
enable = true
contactInfoTitle = "CONTACT <span>INFO</span> "
blogTitle = "LATEST <span>BLOG POSTS</span>"
galleryTitle = "PHOTO <span>STREAM</span>"
socialTitle = "Follow <span>US</span>"

############################ footer contact item
[[params.footer.contactItem]]
title = "Telephone"
icon = "fa fa-phone"
content = "016742 323313"
link = "tel:01612345678"

[[params.footer.contactItem]]
title = "Address"
icon = "fa fa-map-marker"
content = "2046 Blue Spruce Lane Laurel Canada"
link = "https://maps.app.goo.gl/GvGx9KQLvUewKz769"

[[params.footer.contactItem]]
title = "E-mail"
icon = "fa fa-envelope"
content = "rest@gmail.com"
link = "mailto:rest@gmail"

######################### footer gallery
[[params.footer.gallery]]
image = "images/slider/slider-img-1.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-2.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-3.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-4.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-1.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-2.jpg"

######################## Social Icon 
[[params.footer.socialLink]]
icon = "facebook"
link = "https://fb.com/themefisher"

[[params.footer.socialLink]]
icon = "twitter"
link = "https://fb.com/themefisher"

[[params.footer.socialLink]]
icon = "dribbble"
link = "https://fb.com/themefisher"

[[params.footer.socialLink]]
icon = "instagram"
link = "https://fb.com/themefisher"
